### ISSUE TITLE
10 Gbps support

### ISSUE THREAD

**Issue by mclayton1000** [Xilinx/open-nic#11]
Hello everyone,

can the OpenNIC support 10 Gbps speed?

Thank you, best regards.

**Comment by cneely-xlnx** [comment]
Hi @mclayton1000,
No, it doesn’t currently, but of course if someone in the community wanted to do this, then this could be of interest to other potential users.

Best regards,
--Chris

**Comment by aneesullah** [comment]
Hi @cneely-xlnx, 
Is there anyway to sort of emulate 10G/25G speed on existing setup? What I believe is that the entire 322 Mhz clock domain including the MAC and physical layers needs to be changed? Can you list the changes that needs to be done to understand how much additional work is required? 
Thanks a lot
Anees

**Comment by cneely-xlnx** [comment]
Hi @aneesullah,

I can't really recommend quick ways to emulate running lower speeds.  There are other projects that might be more appropriate using earlier devices and such, e.g.: https://netfpga.org/NetFPGA-SUME.html

We had designed/intended for the open-nic to run at 100Gbps, and we mainly want to encourage that use case.

Best regards,
--Chris
